### ISSUE TITLE
C# ?

### ISSUE THREAD

**Issue by ignatandrei** [netgusto/nodebook#40]
What about C# / .NET ?

**Comment by netgusto** [comment]
I'm not familiar with that language. Could you maybe push a PR inspired by this one to implement these languages? https://github.com/netgusto/nodebook/pull/41

I'd happily merge it!

**Comment by netgusto** [comment]
@ignatandrei ?

**Comment by ignatandrei** [comment]
C# is not so different from Java. 
See https://www.carlosag.net/tools/codetranslator/ java to C# .

**Comment by netgusto** [comment]
It's not about the syntax, it's about:
* how to compile and run it on command line
* what prebuilt docker hub image would be a good fit to run it

**Comment by netgusto** [comment]
Done in 0.1.23

**Comment by netgusto** [comment]
Done in 0.1.23

**Comment by ignatandrei** [comment]
https://github.com/filipw/dotnet-script  - for running scripts

**Comment by ignatandrei** [comment]
https://hub.docker.com/r/microsoft/dotnet/

**Comment by netgusto** [comment]
Thanks! The later is what I ended up using for C# support in v0.1.23

**Comment by ignatandrei** [comment]
I did not have time to look into your project. However, can you now integrate C# into it?

**Comment by netgusto** [comment]
Yes. It is already done :)
