### ISSUE TITLE
How to use it on Mac? please help me

### ISSUE THREAD

**Issue by henyjone** [netgusto/nodebook#81]
I downloaded nodebook-mac.dms , but I don't know how to use it on Mac. Please help me

**Comment by seanpowell** [comment]
Hello! 

The quickest way:

1. Rename the file 'nodebook' without an extension. So remove anything past 'nodebook' in the name.  Open up your terminal and run the file directly like:
`~/Downloads/nodebook help`

A better way:

1. Move the file to a folder that is in your PATH.
2. Rename the file 'nodebook' without an extension. So remove anything past 'nodebook' in the name. 
3. Make sure it has the appropriate permissions.
``` bash
  chmod 755 /PATH/TO/FILE/nodebook
```
4. Create an empty folder to store your new notebooks.  Can be placed anywhere in your file system. Just remember/make note of the path. e.g. ~/path/to/notebooks
5. Open up your terminal and run the program:
``` bash
 nodebook web ~/path/to/notebooks
```

**Comment by netgusto** [comment]
Hey @seanpowell thank you for the detailed steps, it's very helpful!
